src/BecketLee/Models/BecketLeeRole.cs
using System;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;

namespace BecketLee.Models
{
    public class BecketLeeRole : IdentityRole
    {
        
        public string Description { get; set; }
        public DateTime CreatedDate { get; set; } = DateTime.UtcNow;

        public string IPAddress { get; set; }

    }
}

src/BecketLee/Controllers/Web/AppController.cs
using BecketLee.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;

namespace BecketLee.Controllers.Web
{
    public class HomeController : Controller
    {
        private readonly IEventRepository _repository;
        private IConfigurationRoot _config;
        private readonly ILogger _logger;

        public HomeController( 
            IEventRepository repository,
            IConfigurationRoot config, 
            ILogger<HomeController> logger)
        {
            _repository = repository;
            _config = config;
            _logger = logger;
        }

        public IActionResult Index()
        {           
            return View( _repository.GetCurrentEvents());
        }


        public IActionResult OurServices()
       {
           return View();
       }

        public IActionResult FirmHistory()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }


        public IActionResult UnauthorizedView()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

src/BecketLee/Controllers/Web/EditController.cs
using System.IO;
using System.Threading.Tasks;
using BecketLee.Data;
using BecketLee.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Net.Http.Headers;

public class EditController : Controller
{
    private readonly IHostingEnvironment _environment;
    private BecketLeeContext _context;

    public EditController( IHostingEnvironment environment, BecketLeeContext context )
    {
        _environment = environment;
        _context = context;
    }

    public IActionResult EditBio()
    {
        var data = _context.PartnerBiographies;
        var model = new PartnerViewModel();
        return View( model );
    }

    [HttpPost]
    public async Task<IActionResult>EditBio(PartnerViewModel model)
    {
        await UploadFile( model );

        return View(model);
    }


    [HttpPost]
    public async Task<bool> UploadFile(PartnerViewModel model)
    {
        var file = model.File;
        if ( file == null ) return false;
        
        if ( file.Length > 0 )
        {
            var uploadName = ContentDispositionHeaderValue.Parse( file.ContentDisposition ).FileName.Trim( '"' );
            var fileName = uploadName.Substring( uploadName.LastIndexOf( '\\' ) + 1 );
            var streamName = Path.Combine( _environment.WebRootPath, "image\\BioImage", fileName );
            using (var filestream = System.IO.File.Create(streamName))
            {
                if( model.IsImage( file ) )
                {
                    model.FileUrl = @"/image/BioImage" + $@"/{fileName}";
                    model.FileName = fileName;
                    model.File = file;

                    await file.CopyToAsync( filestream );
                    await filestream.FlushAsync();
                }
                else
                    return false;
            }
        }
        return true;
    }


}

src/BecketLee/Views/App/OurServices.cshtml
@{
    ViewBag.Title = "Services";
}

<div class="row">
    <div class="col-md-12">
        <div class="panel with-nav-tabs panel-default">
            <div class="panel-heading"><h2>Our Services</h2>
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#tabClaims" data-toggle="tab">Claims Filing and Case Administration</a></li>
                    <li><a href="#tabLitigation" data-toggle="tab">Litigation Services</a></li>
                    <li><a href="#tabSystem7" data-toggle="tab">System 7<span class="SuperScript">SM</span></a></li>
                </ul>
            </div>
            <div class="panel-body">
                <div class="tab-content">
                    <div class="tab-pane fade in active" id="tabClaims">
                        <p>
                            Let our team of dedicated bankruptcy professionals relieve you of the
                            day-to-day burden of managing your bankruptcy portfolio. We have the expertise,
                            experience, software and staff to manage:
                        </p>
                        <ul>
                            <li>Electronic Claims Filing</li>
                            <li>Electronic Bankruptcy Noticing</li>
                            <li>E-mail Notices from CM/ECF Courts</li>
                            <li>Redaction of Social Security Numbers</li>
                            <li>Electronic Payment Vouchers</li>
                            <li>Transfers of Claim</li>
                        </ul>
                        <p>
                            Partnering with Becket & Lee LLP also solves other common bankruptcy management issues, such as maintaining adequate staff levels as bankruptcies increase and decrease, and absorbing and processing the volume of paper mail that still keeps coming. We will monitor your cases to make sure your claims are properly filed, and that you get the recoveries which you are entitled to on your bankrupt accounts. You owe it to your bottom line to see how Becket & Lee can make a difference for you.
                        </p>
                    </div>
                    <div class="tab-pane fade" id="tabLitigation">
                        <p>
                            Becket & Lee stands ready to apply its long experience with the Bankruptcy Courts to help you develop a cost-efficient and effective litigation program by providing complete legal services in all Bankruptcy Courts, utilizing a nationwide network of local counsel. At no time, however, does Becket & Lee “refer out” litigation accounts. We retain responsibility for all matters, and you work only with Becket & Lee attorneys, giving you confidence that your litigation is being handled by experts.
                        </p>
                        <p>
                            Among the litigation services we provide are:
                        </p>
                        <ul>
                            <li>Complaints to Determine Dischargeability of Debt</li>
                            <li>Objections to the Debtor’s Discharge</li>
                            <li>Objections to Confirmation of a Plan</li>
                            <li>Motions to Dismiss Under §707</li>
                            <li>Motions for Relief from the Co-Debtor Stay</li>
                            <li>Defense of Objections to Claim</li>
                            <li>Defense of Preference Actions</li>
                            <li>Defense of Trustee Avoidance Actions</li>
                            <li>Defense of Automatic Stay Violation Actions</li>
                            <li>Motions to Lift Automatic Stay</li>
                            <li>Motions to Value Collateral</li>
                            <li>Motions to Allow Administrative Claims</li>
                            <li>Motions for Setoff</li>
                        </ul>
                    </div>
                    <div class="tab-pane fade" id="tabSystem7">
                        <p>
                            Taking advantage of the latest technology and data resources, Becket & Lee has developed "System7<span class="SuperScript">SM</span>", which provides a cost effective method to track bankrupt Chapter 7 accounts. Your Chapter 7 accounts are referred to Becket & Lee, where System7<span class='SuperScript'>SM</span> monitors the bankruptcies until they have been closed by the court. The bankruptcies are regularly scrubbed. If an account is identified as an asset case, it is moved from System7<span class='SuperScript'>SM</span> to our core bankruptcy system. There, a Proof of Claim is generated, filed with the court according to local procedures, and the bankruptcy is monitored for activity and payment.
                        </p>
                        <p>
                            In addition, Becket & Lee’s System7<span class="SuperScript">SM</span> provides an electronic update to our clients when a Chapter 7 bankruptcy has been identified as:
                        </p>
                        <ul>
                            <li>Dismissed and closed by the court</li>
                            <li>Discharged and closed by the court</li>
                            <li>Converted to another chapter</li>
                            <li>Becoming an asset case</li>
                        </ul>
                        <p>
                            Becket & Lee’s System7<span class="SuperScript">SM</span> provides the technology and economies of scale to maximize Proof of Claim recoveries from Chapter 7 portfolios.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

src/BecketLee/Views/App/Services.cshtml
@{
    ViewBag.Title = "Services";
}


<div id="exTab" class="container-fluid">

    <ul class="nav nav-pills ">
        <li class="active ">
            <a href="#1a" data-toggle="tab">Claims Filing and Case Administration</a>
        </li>
        <li>
            <a href="#2a" data-toggle="tab">Litigation Services</a>
        </li>
        <li>
            <a href="#3a" data-toggle="tab">System 7</a>
        </li>
    </ul>
    <div class="tab-content clearfix">
        <div class="tab-pane active" id="1a">
            <p>
                Let our team of dedicated bankruptcy professionals relieve you of the
                day-to-day burden of managing your bankruptcy portfolio. We have the expertise,
                experience, software and staff to manage:
            </p>
            <ul>
                <li>Electronic Claims Filing</li>
                <li>Electronic Bankruptcy Noticing</li>
                <li>E-mail Notices from CM/ECF Courts</li>
                <li>Redaction of Social Security Numbers</li>
                <li>Electronic Payment Vouchers</li>
                <li>Transfers of Claim</li>
            </ul>
            <p>
                Partnering with Becket & Lee LLP also solves other common bankruptcy management issues, such as maintaining adequate staff levels as bankruptcies increase and decrease, and absorbing and processing the volume of paper mail that still keeps coming. We will monitor your cases to make sure your claims are properly filed, and that you get the recoveries which you are entitled to on your bankrupt accounts. You owe it to your bottom line to see how Becket & Lee can make a difference for you.
            </p>

        </div>


        <div class="tab-pane" id="2a">
            <p>
                Becket & Lee stands ready to apply its long experience with the Bankruptcy Courts to help you develop a cost-efficient and effective litigation program by providing complete legal services in all Bankruptcy Courts, utilizing a nationwide network of local counsel.  At no time, however, does Becket & Lee “refer out” litigation accounts.  We retain responsibility for all matters, and you work only with Becket & Lee attorneys, giving you confidence that your litigation is being handled by experts.
            </p>
            <p>
                Among the litigation services we provide are:
            </p>
            <ul>
                <li>Complaints to Determine Dischargeability of Debt</li>
                <li>Objections to the Debtor’s Discharge</li>
                <li>Objections to Confirmation of a Plan</li>
                <li>Motions to Dismiss Under §707</li>
                <li>Motions for Relief from the Co-Debtor Stay</li>
                <li>Defense of Objections to Claim</li>
                <li>Defense of Preference Actions</li>
                <li>Defense of Trustee Avoidance Actions</li>
                <li>Defense of Automatic Stay Violation Actions</li>
                <li>Motions to Lift Automatic Stay</li>
                <li>Motions to Value Collateral</li>
                <li>Motions to Allow Administrative Claims</li>
                <li>Motions for Setoff</li>
            </ul>
        </div>

        <div class="tab-pane" id="3a">
            <p>
                Taking advantage of the latest technology and data resources, Becket & Lee has developed "System7<span class="SuperScript">SM</span>", which provides a cost effective method to track bankrupt Chapter 7 accounts. Your Chapter 7 accounts are referred to Becket & Lee, where System7<span class='SuperScript'>SM</span> monitors the bankruptcies until they have been closed by the court. The bankruptcies are regularly scrubbed.  If an account is identified as an asset case, it is moved from System7<span class='SuperScript'>SM</span> to our core bankruptcy system.   There, a Proof of Claim is generated, filed with the court according to local procedures, and the bankruptcy is monitored for activity and payment.
            </p>
            <p>
                In addition, Becket & Lee’s System7<span class="SuperScript">SM</span> provides an electronic update to our clients when a Chapter 7 bankruptcy has been identified as:
            </p>
            <ul>
                <li>Dismissed and closed by the court</li>
                <li>Discharged and closed by the court</li>
                <li>Converted to another chapter</li>
                <li>Becoming an asset case</li>
            </ul>
            <p>
                Becket & Lee’s System7<span class="SuperScript">SM</span> provides the technology and economies of scale to maximize Proof of Claim recoveries from Chapter 7 portfolios.
            </p>
        </div>
    </div>
</div>

src/BecketLee/Views/App/Unauthorized.cshtml
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h3>You have attempted to access restricted pages.</h3>
        <p>
            If you feel you have reached this page in error, you should retry to be sure you typed the URL
            correctly. If you still cannot access the page, contact or speak to the web manager about your access level.
        </p>
    </div>
</div>

src/BecketLee/Views/Edit/EditBio.cshtml
@using System.IO
@using BecketLee.ViewModels
@model BecketLee.ViewModels.PartnerViewModel
@{
    ViewBag.Title = "Edit Bio";
}

<form asp-action="EditBio" asp-controller="Edit" method="post" enctype="multipart/form-data">
    @section scripts{
        <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
        <script src="~/ckeditor/ckeditor.js"></script>
        <script language="javascript">
            CKEDITOR.replace('BiographyHtml');
        </script>
    }
    
    <div class="col-md-8">
        <div class="form-group">
            <label asp-for="PartnerName">Name</label>
            <input asp-for="PartnerName" class="form-control" />
            <span asp-validation-for="PartnerName"></span>
        </div>
        <div class="form-group">
            <label asp-for="BiographyHtml">Biography</label>
            <textarea type="text" asp-for="BiographyHtml" name="BiographyHtml" id="BiographyHtml" class="form-control"></textarea>
            <span asp-validation-for="BiographyHtml"></span>
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <label asp-for="File">Photo Upload</label>
            <input asp-for="File" />
        </div>

        <div class="form-group">            
            <img src="@Model.FileUrl"  alt="@Model.PartnerName" class="partnerImage" asp-append-version="true"/>
        </div>
        <div class="form-group">
            <label asp-for="FileName">@Model.FileName</label>
        </div>

        <div class="form-group">
            <input type="submit" value="Save All" />
        </div>
    </div>
</form>

src/BecketLee/Views/Partner/Bio.cshtml
@model BecketLee.ViewModels.PartnerViewModel
@{
    ViewBag.Title = @Model.PartnerName;
}

<div class="container-fluid">
    
    <div class="col-md-8">
        <div><h3>@Model.PartnerName</h3></div>
        <div>
            <div><h4>Biography</h4></div>
            <div id="BiographyHtml">@Html.Raw(Model.BiographyHtml)</div>
        </div>
    </div>
    <div class="col-md-4">
        <div>
            <img src="@Model.FileUrl" alt="@Model.PartnerName" class="partnerImage"/>
        </div>
    </div>
</div>

src/BecketLee/Views/Partner/Partners.cshtml
@using BecketLee.ViewModels
@model IEnumerable<PartnerViewModel>
@{
    ViewBag.Title = "Partners";
}
<div class="row">
    <div class="col-md-12">
        <div class="col-md-10 col-md-offset-1">
            <h3>Becket & Lee Partners</h3>
            <p style="text-align:justify">
                The Partners of Becket & Lee are leaders in their highly specialized area of the law. The Firm carries an AV® rating from Martindale Hubbel. An AV® certification mark is a significant rating accomplishment - a testament to the fact that a lawyer's peers rank him or her at the highest level of professional excellence.
            </p>
        </div>
        </div>
</div>
<div class="row">
    <div class="col-md-6 col-md-offset-3 ">
        <br /><br />
        <ul class="list-inline center-block text-center">
            @foreach (var item in Model)
            {
                <li>
                    <div class="partnerSelection">
                        <a asp-action="Bio" asp-controller="Partner" asp-route-id="@item.PartnerName">
                            <img src="@item.FileUrl" alt="@item.PartnerName" class="partnerAvatar" asp-append-version="true" />
                            <br />
                            @item.PartnerName

                        </a>
                    </div>

                </li>
            }
        </ul>
    </div>
</div>

src/BecketLee/Views/Users/AddEditUser.cshtml
@model BecketLee.ViewModels.UserViewModel

<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h1>
             @{
                    if( string.IsNullOrEmpty( Model.Id ) )
                    {
                        <span>Add</span>
                    }
                    else
                    {
                        <span>Edit</span>
                    }
                } User
        </h1>
        @using (Html.BeginForm( "AddEditUser", "Users", FormMethod.Post ))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary()

            <div class="form-group">
                @Html.LabelFor( x => x.UserName, new { @class = "control-label" } )
                @Html.TextBoxFor( x => x.UserName, new { @class = "form-control" } )
                @Html.ValidationMessageFor( x => x.UserName )

            </div>
            <div class="form-group">
                @Html.LabelFor( x => x.Email, new { @class = "control-label" } )
                @Html.TextBoxFor( x => x.Email, new { @class = "form-control" } )
                @Html.ValidationMessageFor( x => x.Email )

            </div>
            <div class="form-group">
                @Html.LabelFor( x => x.Password, new { @class = "control-label" } )
                @Html.TextBoxFor( x => x.Password, new { @class = "form-control" } )
                @Html.ValidationMessageFor( x => x.Password )

            </div>
            <div class="form-group">
                @Html.LabelFor( x => x.ConfirmPassword, new { @class = "control-label" } )
                @Html.TextBoxFor( x => x.ConfirmPassword, new { @class = "form-control" } )
                @Html.ValidationMessageFor( x => x.ConfirmPassword )
            </div>
            <div class="form-group">
                @Html.LabelFor( x => x.UserRoles, new { @class = "control-label" } )
                <ul asp-for="UserRoles" class="control-label">
                    @foreach (var item in @Model.UserRoles)
                    {
                        <li>@item.RoleName</li>
                    }
                </ul>
            </div>
            <div class="pull-right form-group">
                <a asp-controller="Users" asp-action="Index" class="btn btn-sm btn-default">Cancel</a>
                <a asp-controller="Users" asp-action="UserRole" asp-route-id="@Model.Id" class="btn btn-sm btn-info"><i class="fa fa-pencil"> </i> Edit Roles</a>
                <input type="submit" class="btn btn-sm btn-success" value="Save" />
            </div>

        }

    </div>
</div>

src/BecketLee/Views/Users/RegisterUser.cshtml
@model BecketLee.ViewModels.UserViewModel

<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h1>Add new user</h1>
        @using (Html.BeginForm( "RegisterUser", "Users", FormMethod.Post ))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary()

            <div class="form-group">
                @Html.LabelFor( x => x.UserName, new { @class = "control-label" } )
                @Html.TextBoxFor( x => x.UserName, new { @class = "form-control" } )
                @Html.ValidationMessageFor( x => x.UserName )

            </div>
            <div class="form-group">
                @Html.LabelFor( x => x.Email, new { @class = "control-label" } )
                @Html.TextBoxFor( x => x.Email, new { @class = "form-control" } )
                @Html.ValidationMessageFor( x => x.Email )

            </div>
            <div class="form-group">
                @Html.LabelFor( x => x.Password, new { @class = "control-label" } )
                @Html.TextBoxFor( x => x.Password, new { @class = "form-control" } )
                @Html.ValidationMessageFor( x => x.Password )

            </div>
            <div class="form-group">
                @Html.LabelFor( x => x.ConfirmPassword, new { @class = "control-label" } )
                @Html.TextBoxFor( x => x.ConfirmPassword, new { @class = "form-control" } )
                @Html.ValidationMessageFor( x => x.ConfirmPassword )
            </div>
            <div class="form-group">
                @Html.LabelFor( x => x.UserRoles, new { @class = "control-label" } )
                <ul asp-for="UserRoles" class="control-label">
                    @foreach (var item in @Model.UserRoles)
                    {
                        <li>@item.RoleName</li>
                    }
                </ul>
            </div>
            <div class="pull-right form-group">
                <a asp-controller="Users" asp-action="Index" class="btn btn-sm btn-default">Cancel</a>
                <input type="submit" class="btn btn-sm btn-success" value="Save" />
            </div>

        }

    </div>
</div>